---
- hosts: kubernetes
#  become: true
  user: root

  tasks:
  - name: deploy igpproject app on kubernetes
    command: kubectl apply -f igpproject-deployment.yml

  - name: create service for igpproject
    command: kubectl apply -f igpproject-service.yml

  - name: update deployment with new pods if image updated in docker hub
    command: kubectl rollout restart deployment.apps/ankitsoni301188-igpproject